---
- name: Create and Configure EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    key_name: Mumbai
    region: ap-south-1a
    instance_type: t2.micro
    ami: ami-0f8ca728008ff5af4
    security_group: easypay-1

  tasks:

  - name: Launching EC2 Instance
    ec2:
      key_name: "{{ key_name }}"
      region: "{{ region }}"
      instance_type: "{{ instance_type }}"
      image: "{{ ami }}"
      wait: yes
      group_id: "{{ security_group }}"
      count: 1
      instance_tags:
        Name: my_instance
    register: ec2

  - name: Add the new instance to the host group
    add_host:
      name: "{{ ec2.instances[0].public_dns_name }}"
      groups: launched

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ ec2.instances[0].public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320

  - name: Update the apt package index
    become: yes
    become_user: ubuntu
    apt:
      update_cache: yes

  - name: Install nginx web server
    become: yes
    become_user: ubuntu
    apt:
      name: nginx
      state: latest

  - name: Start nginx web server
    become: yes
    become_user: ubuntu
    service:
      name: nginx
      state: started

